version: '3.8'

services:
  frontend:
    build: .
    container_name: calculadora_save
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  backend:
    build: ./api
    container_name: calculadora_backend
    environment:
      - TESS_API_KEY=1580872|aOUL2wWYyBU72GQWvPm89jjks531kamQ7qodjjWzb68f3a9d
    restart: always

volumes:
  caddy_data:
  caddy_config:
