version: '3.8'

services:
  frontend:
    build: .
    container_name: calculadora_save
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

volumes:
  caddy_data:
  caddy_config:
